from fpdf import FPDF
import os
from datetime import datetime
from PIL import Image

class ForensicReport(FPDF):
    def sanitize_txt(self, txt):
        # FIX ERROR FPDF: Menghapus karakter unicode aneh yang bikin PDF gagal dibuat
        return str(txt).encode('latin-1', 'replace').decode('latin-1')

    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'VeriPix - Digital Forensic Report', 0, 1, 'C')
        self.set_line_width(0.5)
        self.line(10, 20, 200, 20)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 8, self.sanitize_txt(f"  {label}"), 0, 1, 'L', 1)
        self.ln(4)

    def generate_pdf(self, image_path, metadata, analysis_type, result_image_path, output_filename="Report.pdf"):
        self.add_page()
        
        # 1. Informasi Umum
        self.set_font('Arial', '', 10)
        self.cell(0, 6, self.sanitize_txt(f"Analysis Type  : {analysis_type}"), 0, 1)
        self.cell(0, 6, self.sanitize_txt(f"Timestamp      : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), 0, 1)
        self.cell(0, 6, self.sanitize_txt(f"Investigator   : Automated VeriPix System"), 0, 1)
        self.ln(5)

        # 2. File Metadata (Tabel)
        self.chapter_title('File Information & Metadata')
        self.set_font('Arial', '', 9)
        
        keys_priority = ['File Name', 'File Size', 'MD5 Checksum', 'Format', 'Dimensions', 'Make', 'Model', 'Software', 'DateTime']
        
        for key in keys_priority:
            if key in metadata:
                val = str(metadata[key])
                if len(val) > 80: val = val[:77] + "..."
                self.cell(45, 6, self.sanitize_txt(key), 1)
                self.cell(145, 6, self.sanitize_txt(val), 1, 1)
        self.ln(10)

        # 3. Bukti Visual
        self.chapter_title('Visual Evidence')
        
        y_pos = self.get_y()
        self.set_font('Arial', 'B', 10)
        self.cell(90, 8, "Original Image", 0, 0, 'C')
        self.cell(10, 8, "", 0, 0)
        self.cell(90, 8, "Analyzed Result", 0, 1, 'C')
        
        img_width = 90
        try:
            if os.path.exists(image_path):
                # FPDF kadang sensitif dengan gambar PNG transparan, tapi kita coba tangkap error-nya
                self.image(image_path, x=10, y=y_pos+10, w=img_width)
            
            if result_image_path and os.path.exists(result_image_path):
                self.image(result_image_path, x=110, y=y_pos+10, w=img_width)
        except Exception as e:
            self.cell(0, 10, self.sanitize_txt(f"[Error rendering visual preview in PDF: {str(e)}]"), 0, 1)

        self.set_y(y_pos + 80) 
        self.ln(10)
        
        # 4. Kesimpulan
        self.chapter_title('Analysis Conclusion')
        self.set_font('Arial', '', 10)
        conclusion = "Based on the visual analysis performed above, please review the highlighted areas.\n"
        if "ELA" in analysis_type:
            conclusion += "- In ELA mode, bright or multi-colored areas indicate different compression levels compared to the background, which is a strong indicator of digital manipulation (splicing/text overlay)."
        elif "SIFT" in analysis_type:
            conclusion += "- In SIFT mode, red lines connecting two different areas indicate identical feature vectors, strongly suggesting a Copy-Move (cloning) forgery."
        
        self.multi_cell(0, 5, self.sanitize_txt(conclusion))
        self.ln(10)

        self.set_font('Arial', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.multi_cell(0, 4, "Disclaimer: This report is generated by an automated computer vision tool. Results should be verified by a human expert. False positives may occur due to high compression or low resolution.")

        try:
            self.output(output_filename)
            return True, output_filename
        except Exception as e:
            return False, f"Gagal membuat file PDF. Detail Error: {str(e)}"